### ISSUE TITLE
sometimes deletes to many characters

### ISSUE THREAD

**Issue by max397574** [Krafi2/jeskape.nvim#2]
sometimes when I esc with jk too many characters get deleted (just the last one I typed) I can't exactly tell when and when not
when I just to it multiple times it works somewhen

**Comment by Krafi2** [comment]
Can you share your config? I cant reproduce this with mine.

**Comment by max397574** [comment]
require("jeskape").setup({
  mappings = {
    ["c"] = {
      ["c"] = "<c-o>:lua require'utils'.append_comma()<CR>",
    },
    j = {
      k = "<esc>",
      j = "<esc>o",
      l = "<c-o>:lua print('test')<CR>",
    },
  },
})


sometimes when I hit jk it just deletes the last character

**Comment by Krafi2** [comment]
Should be fixed now! Also, if you want to map commands in insert mode, you have to use `<cmd>lua print("test")<cr>`, because a colon will just insert `:`.

**Comment by max397574** [comment]
oh I have <c-o> but that somehow didn't get copied

**Comment by max397574** [comment]
I'll update and close this if I don't experience any problems in the next few hours

**Comment by max397574** [comment]
no issues so far
