### ISSUE TITLE
[discussions] mapping with fzf plugin

### ISSUE THREAD

**Issue by cutbypham** [Krafi2/jeskape.nvim#4]
- finally i found a way mapping with fzf.vim plugin 😅

```lua
        f = {
            p = "<cmd>call fzf#vim#complete#path('fd')<enter>",
            w = "<cmd>call fzf#vim#complete#word({'window': { 'width': 0.2, 'height': 0.9, 'xoffset': 1 }})<enter>",
        },
```

my full jeskape config: https://github.com/thuanpham2311/dotfiles/blob/master/nvim/after/plugin/jeskape.lua

**Comment by Krafi2** [comment]
Ah, I will clarify that in the README.

**Comment by Krafi2** [comment]
I've updated the readme with an example and mentioned the relevant docs. Hopefully that should prevent future confusion.
