### ISSUE TITLE
Timout deosn't seem to be working

### ISSUE THREAD

**Issue by svban** [Krafi2/jeskape.nvim#6]
jeskape is still using vim.o.timeoutlen instead of my custom timeout=80 
{
        "Krafi2/jeskape.nvim",
        config = function()
            require("jeskape").setup {
                timeout = 80, 
                mappings = {
                    jj = "()<left>",
                    kk = "{}<left>",
                },
            }
        end,
    }

EDIT: Issue solved, looks like some other plugin was overriding it. You can delete this.

**Comment by Krafi2** [comment]
Glad you figured it out
